name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [check, test, build]
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          enable-cache: true
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: cp env/env.staging.ts src/env.ts
      - run: pnpm ${{ matrix.task }}
